#!/bin/sh
# SPDX-FileCopyrightText: 2022 Lars Geyer-Blaumeiser <lars@lgblaumeiser.de>
# SPDX-License-Identifier: MIT
./openapi-generator-cli \
    validate \
    -i ../../ProjectTimeManager2.Api/ptm-api.yaml \
    --recommend
